### ISSUE TITLE
Show deep diff on failure to match

### ISSUE THREAD

**Issue by tru-hamish** [Originate/chai-match-pattern#11]
Firstly, many thanks for `chai-match-pattern`!

I am wondering if it might be possible to show a deep diff on failure to `matchPattern()`. The following test:
```
const { isAsyncFunction } = require('util/types');
describe('test', () => {
  it('should fail here on deep equality', () => {
    const actual = { a: 1, b: { c: async () => {} } };
    const expected = { a: 1, b: { c: isAsyncFunction } };
    expect(actual).to.deep.equal(expected);
  });
  it('should pass here on deep match', () => {
    const actual = { a: 1, b: { c: async () => {} } };
    const expected = { a: 1, b: { c: isAsyncFunction } };
    expect(actual).to.matchPattern(expected);
  });
  it('should fail here on deep match', () => {
    const actual = { a: 1, b: { c: 2 } };
    const expected = { a: 1, b: { c: isAsyncFunction } };
    expect(actual).to.matchPattern(expected);
  });
});
```

gives the output:

```
  test
    1) should fail here on deep equality
    ✔ should pass here on deep match
    2) should fail here on deep match


  1 passing (8ms)
  2 failing

  1) test
       should fail here on deep equality:

      AssertionError: expected { a: 1, b: { c: [Function c] } } to deeply equal { a: 1, b: { c: [Function isAsyncFunction] } }
      + expected - actual

       {
         "a": 1
         "b": {
      -    "c": "async () => {}"
      +    "c": [Function]
         }
       }
      
      at Context.<anonymous> (test/lib/matchPattern-test.js:9:28)
      at processImmediate (node:internal/timers:476:21)

  2) test
       should fail here on deep match:

      AssertionError: {c: 2} didn't match target {c: 'function isAsyncFunction() {...}'}
      + expected - actual


      at Context.<anonymous> (test/lib/matchPattern-test.js:19:23)
      at processImmediate (node:internal/timers:476:21)
```

Is it possible to persuade `matchPattern()` to provide the deep `+ expected - actual` diff like `deep.equal()` does?

**Comment by tru-hamish** [comment]
I dug deeper into this and learned a lot more about `chai` plugins.

What I've requested here is trivially possible by changing:
```
    this.assert(
      !check,
      check,
      'expected #{this} to not match the given pattern',
      pattern, obj,
    );
```

to:
```
    this.assert(
      !check,
      check,
      'expected #{this} to not match the given pattern',
      pattern, obj,
      _chai.config.showDiff,
    );
```

But it doesn't really help much, because the diff is static -- it's just a string diff on the string description of the actual vs expected objects.

Patterns that would have matched are shown as differences... and this is probably why you wrote it this to exclude the diff in the first place.

So I shall close the issue with this comment, with apologies for the noise.
